spacing         = 1
padding         = 1
hide_ascii      = true
separator       = "‚ñ∏"
key_color       = "Magenta"
separator_color = "Yellow"

[palette]
glyph = "‚ñ® "
type = "Dark"
visible = true

[bar]
visible         = false

[box]
title           = "‚îÄ‚î§ üçÅ ·¥õ è'Íú± ·¥ò·¥ú·¥õ·¥á Ä üçÅ ‚îú"
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 1
y               = 1

[keys]
host            = "Host"
machine         = "PC"
distro          = "Linux"
shell           = "Shell"
de              = "DE"
wm              = "WM"
resolution      = "Res"
cpu             = "CPU"
gpu             = "GPU"
memory          = "RAM"
